phrase:
  project_id: 2f5ee8c5dc073d8fa4f8a1d95bcf0103

  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json

