phrase: 
project_id: 1b97950ab77ee8165fd7309196217136

#NAVAPP   
 push:
    sources:
    
      - file: ./NAVAPP/en-GB/<tag>.xml
        params:
          file_format: xml
          locale_id: en-GB
          update_translations: true
          autotranslate: true

  #amiGO
      - file: ./AmiGO/en-GB/<tag>.xml
        params:
          file_format: xml
          locale_id: en-GB
          update_translations: true
          autotranslate: true

  
  pull:
    targets:
    #NAVAPP
      - file: ./NAVAPP/de/<tag>.xml
        params:
          locale_id: de
          file_format: xml
          tags: de_navapp

     #amiGO
      - file: ./AmiGO/de/<tag>.xml
        params:
          locale_id: de
          file_format: xml
          tags: de.amigo
