phrase: 
  #project_id: 1b97950ab77ee8165fd7309196217136

  push:
    sources:
      # NAVAPP    
      - file: ./NAVAPP/en-GB/<tag>.xml
        project_id: 1b97950ab77ee8165fd7309196217136
        params:
          file_format: xml
          locale_id: en-GB
          update_translations: true
          autotranslate: true

      # amiGO
      - file: ./AmiGO/en-GB/<tag>.xml
        project_id: 5dc64e210b821d1e7c995913f68a646c 
        params:
          file_format: xml
          locale_id: en-GB
          update_translations: true
          autotranslate: true
  
  pull:
    targets:
      # NAVAPP
      - file: ./NAVAPP/de/<tag>.xml
        project_id: 1b97950ab77ee8165fd7309196217136
        params:
          locale_id: de
          file_format: xml
          tags: de_navapp

      # amiGO
      - file: ./AmiGO/de/<tag>.xml
        project_id: 5dc64e210b821d1e7c995913f68a646c
        params:
          locale_id: de
          file_format: xml
          tags: de.amigo

