phrase:
  project_id: f21e142885498b579f5d22a7411e548f

  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: de,it,fr,es,da,nl

