phrase:
  project_id: 1b97950ab77ee8165fd7309196217136
  
  push:
    sources:
      - file: ./NAVAPP/en-GB/<tag>.xml
        params:
          file_format: xml
          locale_id: en-GB
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./letstest/NAVAPP/de/*.xml
        project_id: 1b97950ab77ee8165fd7309196217136
        params:
          file_format: xml

