phrase:
  project_id: 5dc64e210b821d1e7c995913f68a646c

  push:
    sources:
      - file: ./letstest/NAVAPP/en-GB/*.xml
        params:
          file_format: xml
          locale_id: en-GB
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./letstest/NAVAPP/de/*.xml
        params:
          file_format: xml
          locale_id: de
          

